package com.nexussoft.verbum.feature.scripture.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.nexussoft.verbum.feature.scripture.R

@Composable
internal fun accountText(key: String): String = stringResource(when (key) {
    "account" -> R.string.account_account
    "welcome" -> R.string.account_welcome
    "intro" -> R.string.account_intro
    "signIn" -> R.string.account_sign_in
    "register" -> R.string.account_register
    "anonymous" -> R.string.account_anonymous
    "later" -> R.string.account_later
    "close" -> R.string.account_close
    "back" -> R.string.account_back
    "email" -> R.string.account_email
    "password" -> R.string.account_password
    "confirm" -> R.string.account_confirm
    "show" -> R.string.account_show
    "hide" -> R.string.account_hide
    "reset" -> R.string.account_reset
    "forgot" -> R.string.account_forgot
    "sendReset" -> R.string.account_send_reset
    "signInTitle" -> R.string.account_sign_in_title
    "signInBody" -> R.string.account_sign_in_body
    "registerTitle" -> R.string.account_register_title
    "registerBody" -> R.string.account_register_body
    "resetTitle" -> R.string.account_reset_title
    "resetBody" -> R.string.account_reset_body
    "resetSent" -> R.string.account_reset_sent
    "guest" -> R.string.account_guest
    "guestBody" -> R.string.account_guest_body
    "existingGuest" -> R.string.account_existing_guest
    "accountBody" -> R.string.account_account_body
    "verified" -> R.string.account_verified
    "unverified" -> R.string.account_unverified
    "verify" -> R.string.account_verify
    "refresh" -> R.string.account_refresh
    "verificationSent" -> R.string.account_verification_sent
    "signOut" -> R.string.account_sign_out
    "signOutBody" -> R.string.account_sign_out_body
    "delete" -> R.string.account_delete
    "deleteTitle" -> R.string.account_delete_title
    "deleteBody" -> R.string.account_delete_body
    "deleteGuestBody" -> R.string.account_delete_guest_body
    "deleted" -> R.string.account_deleted
    "cancel" -> R.string.account_cancel
    "working" -> R.string.account_working
    "invalidEmail" -> R.string.account_invalid_email
    "passwordRequired" -> R.string.account_password_required
    "passwordTooShort" -> R.string.account_password_too_short
    "passwordMismatch" -> R.string.account_password_mismatch
    "credentials" -> R.string.account_credentials
    "emailInUse" -> R.string.account_email_in_use
    "network" -> R.string.account_network
    "tooManyRequests" -> R.string.account_too_many_requests
    "disabled" -> R.string.account_disabled
    "configuration" -> R.string.account_configuration
    "recentLoginRequired" -> R.string.account_recent_login_required
    "unexpected" -> R.string.account_unexpected
    "usageTitle" -> R.string.usage_usage_title
        "plan_guest" -> R.string.usage_plan_guest
        "plan_free" -> R.string.usage_plan_free
        "plan_premium" -> R.string.usage_plan_premium
        "usageAsk" -> R.string.usage_usage_ask
        "usageTTS" -> R.string.usage_usage_t_t_s
        "usageVoice" -> R.string.usage_usage_voice
        "usageReset" -> R.string.usage_usage_reset
        "usageCache" -> R.string.usage_usage_cache
        "usageUnavailable" -> R.string.usage_usage_unavailable
        "usageRestricted" -> R.string.usage_usage_restricted
        "limitTitle" -> R.string.usage_limit_title
        "limitBody" -> R.string.usage_limit_body
        "limitPlanTitle" -> R.string.usage_limit_plan_title
        "limitPlanBody" -> R.string.usage_limit_plan_body
        "limitTemporaryTitle" -> R.string.usage_limit_temporary_title
        "limitSessionTitle" -> R.string.usage_limit_session_title
        "limitRateTitle" -> R.string.usage_limit_rate_title
        "profile" -> R.string.profile_profile
    "yourReadingSpace" -> R.string.profile_your_reading_space
    "profileGuestBody" -> R.string.profile_profile_guest_body
    "createYourAccount" -> R.string.profile_create_your_account
    "yourJourney" -> R.string.profile_your_journey
    "journeyBeginning" -> R.string.profile_journey_beginning
    "journeyContinuing" -> R.string.profile_journey_continuing
    "readingDays" -> R.string.profile_reading_days
    "chaptersOpened" -> R.string.profile_chapters_opened
    "continueReading" -> R.string.profile_continue_reading
    "readingSection" -> R.string.profile_reading_section
    "bibleVersion" -> R.string.profile_bible_version
    "bibleVersionBody" -> R.string.profile_bible_version_body
    "bibleComparisonBody" -> R.string.profile_bible_comparison_body
    "bibleLanguage" -> R.string.profile_bible_language
    "bibleLanguageBody" -> R.string.profile_bible_language_body
    "readingPreferences" -> R.string.profile_reading_preferences
    "audioVoice" -> R.string.profile_audio_voice
    "audioBody" -> R.string.profile_audio_body
    "voiceBody" -> R.string.profile_voice_body
    "yourVerbum" -> R.string.profile_your_verbum
    "savedPassages" -> R.string.profile_saved_passages
    "highlights" -> R.string.profile_highlights
    "notes" -> R.string.profile_notes
    "readingHistory" -> R.string.profile_reading_history
    "historyBody" -> R.string.profile_history_body
    "historyEmpty" -> R.string.profile_history_empty
    "preferencesSection" -> R.string.profile_preferences_section
    "appearance" -> R.string.profile_appearance
    "automatic" -> R.string.profile_automatic
    "light" -> R.string.profile_light
    "dark" -> R.string.profile_dark
    "notifications" -> R.string.profile_notifications
    "notificationsBody" -> R.string.profile_notifications_body
    "appLanguage" -> R.string.profile_app_language
    "appLanguageBody" -> R.string.profile_app_language_body
    "verbumSection" -> R.string.profile_verbum_section
    "help" -> R.string.profile_help
    "helpReading" -> R.string.profile_help_reading
    "helpSaving" -> R.string.profile_help_saving
    "helpOffline" -> R.string.profile_help_offline
    "privacy" -> R.string.profile_privacy
    "privacyLocal" -> R.string.profile_privacy_local
    "privacyAccount" -> R.string.profile_privacy_account
    "privacyAI" -> R.string.profile_privacy_a_i
    "about" -> R.string.profile_about
    "aboutBody" -> R.string.profile_about_body
    "accountDetails" -> R.string.profile_account_details
    "authentication" -> R.string.profile_authentication
    "memberSince" -> R.string.profile_member_since
    "emailPassword" -> R.string.profile_email_password
    "connectedAccount" -> R.string.profile_connected_account
    "displayName" -> R.string.profile_display_name
    "nameNotSet" -> R.string.profile_name_not_set
    "editName" -> R.string.profile_edit_name
    "editNameBody" -> R.string.profile_edit_name_body
    "nameUpdated" -> R.string.profile_name_updated
    "nameRequired" -> R.string.profile_name_required
    "saveChanges" -> R.string.profile_save_changes
    "changeEmail" -> R.string.profile_change_email
    "newEmail" -> R.string.profile_new_email
    "changeEmailBody" -> R.string.profile_change_email_body
    "confirmEmailChange" -> R.string.profile_confirm_email_change
    "emailChangeSent" -> R.string.profile_email_change_sent
    "changePassword" -> R.string.profile_change_password
    "passwordResetBody" -> R.string.profile_password_reset_body
    "deviceLocal" -> R.string.profile_device_local
    "collectionEmpty" -> R.string.profile_collection_empty
    "collectionLoadFailed" -> R.string.profile_collection_load_failed
    "savePassage" -> R.string.profile_save_passage
    "removeBookmark" -> R.string.profile_remove_bookmark
    "openSystemSettings" -> R.string.profile_open_system_settings
    "tryAgain" -> R.string.profile_try_again
    else -> R.string.account_unexpected
})

