// Package memory is a Store over a JSON file — the fixtures the apps ship
// (db/seed/fixtures.json, generated by api/scripts/gen-examples.py). It runs the
// API with no database at all, and it is what the contract tests use. The
// Postgres store must answer exactly like this one; the tests will tell.
package memory

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"verbum/backend/internal/domain"
	"verbum/backend/internal/store"
)

// file is the shape of fixtures.json.
type file struct {
	Sources        []domain.SourceReference  `json:"sources"`
	Entities       []domain.Entity           `json:"entities"`
	Relationships  []domain.Relationship     `json:"relationships"`
	Details        []domain.EntityDetail     `json:"details"`
	Timeline       []domain.TimelineEvent    `json:"timeline"`
	DailyVersePool []domain.PassageReference `json:"dailyVersePool"`
}

type Store struct {
	data     file
	byID     map[string]domain.Entity
	detailBy map[string]domain.EntityDetail
	sourceBy map[string]domain.SourceReference
}

// Load reads a fixtures.json.
func Load(path string) (*Store, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read fixtures: %w", err)
	}
	var f file
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("parse fixtures: %w", err)
	}
	s := &Store{data: f, byID: map[string]domain.Entity{}, detailBy: map[string]domain.EntityDetail{}, sourceBy: map[string]domain.SourceReference{}}
	for _, e := range f.Entities {
		s.byID[e.ID] = e
	}
	for _, d := range f.Details {
		s.detailBy[d.Entity.ID] = d
	}
	for _, src := range f.Sources {
		s.sourceBy[src.ID] = src
	}
	return s, nil
}

var _ store.Store = (*Store)(nil)

func (s *Store) Entity(_ context.Context, id string) (domain.Entity, error) {
	e, ok := s.byID[id]
	if !ok {
		return domain.Entity{}, store.ErrNotFound
	}
	return e, nil
}

func (s *Store) Detail(_ context.Context, id string) (domain.EntityDetail, error) {
	if d, ok := s.detailBy[id]; ok {
		return d, nil
	}
	e, ok := s.byID[id]
	if !ok {
		return domain.EntityDetail{}, store.ErrNotFound
	}
	// No curated facts yet: the entity itself, honestly sourced as editorial.
	return domain.EntityDetail{
		Entity: e, Aliases: []string{}, KeyPassages: []domain.PassageReference{},
		Sources: []domain.SourceReference{s.sourceBy["fixture.source.editorial"]},
	}, nil
}

func (s *Store) Entities(_ context.Context, kind domain.EntityType) ([]domain.Entity, error) {
	out := []domain.Entity{}
	if kind == domain.Passage {
		return out, nil
	}
	for _, e := range s.data.Entities {
		if e.Type == kind {
			out = append(out, e)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, nil
}

func confidence(r domain.Relationship) float64 {
	if r.Confidence == nil {
		return 0
	}
	return *r.Confidence
}

func (s *Store) Neighbors(_ context.Context, id string, limit int) (domain.GraphSnapshot, error) {
	root, ok := s.byID[id]
	if !ok {
		return domain.GraphSnapshot{}, store.ErrNotFound
	}
	// Edges touching the root, strongest first, then by the other end's name.
	var touching []domain.Relationship
	for _, r := range s.data.Relationships {
		if r.SourceID == id || r.TargetID == id {
			touching = append(touching, r)
		}
	}
	other := func(r domain.Relationship) string {
		if r.SourceID == id {
			return r.TargetID
		}
		return r.SourceID
	}
	sort.SliceStable(touching, func(i, j int) bool {
		ci, cj := confidence(touching[i]), confidence(touching[j])
		if ci != cj {
			return ci > cj
		}
		return s.byID[other(touching[i])].Name < s.byID[other(touching[j])].Name
	})
	nodes := []domain.Entity{}
	seen := map[string]bool{id: true}
	for _, r := range touching {
		o := other(r)
		if seen[o] {
			continue
		}
		e, ok := s.byID[o]
		if !ok {
			continue
		}
		seen[o] = true
		nodes = append(nodes, e)
		if len(nodes) == limit {
			break
		}
	}
	edges := []domain.Relationship{}
	for _, r := range s.data.Relationships {
		if seen[r.SourceID] && seen[r.TargetID] {
			edges = append(edges, r)
		}
	}
	return domain.GraphSnapshot{Root: root, Nodes: nodes, Edges: edges}, nil
}

// Context reuses only sourced edges: entities linked to the chapter's passage
// node, entities whose detail cites the chapter, and the passages those
// entities are linked to. Nothing is expanded further (that would imply
// associations nobody asserted).
func (s *Store) Context(_ context.Context, bookID string, chapter int) (domain.PassageContext, error) {
	passageID := fmt.Sprintf("passage.%s.%d", bookID, chapter)
	ids := map[string]bool{}
	sourceIDs := map[string]bool{}
	for _, r := range s.data.Relationships {
		switch passageID {
		case r.SourceID:
			ids[r.TargetID] = true
		case r.TargetID:
			ids[r.SourceID] = true
		default:
			continue
		}
		for _, sid := range r.SourceReferenceIDs {
			sourceIDs[sid] = true
		}
	}
	for _, d := range s.data.Details {
		for _, p := range d.KeyPassages {
			if p.BookID == bookID && p.Chapter == chapter {
				ids[d.Entity.ID] = true
				for _, src := range d.Sources {
					sourceIDs[src.ID] = true
				}
			}
		}
	}
	if len(ids) == 0 {
		return domain.PassageContext{}, store.ErrNotFound
	}
	related := []domain.PassageReference{}
	seenRelated := map[string]bool{}
	for _, r := range s.data.Relationships {
		var o string
		switch {
		case ids[r.SourceID]:
			o = r.TargetID
		case ids[r.TargetID]:
			o = r.SourceID
		default:
			continue
		}
		if !strings.HasPrefix(o, "passage.") || o == passageID {
			continue
		}
		parts := strings.SplitN(o, ".", 3) // passage.<book>.<chapter>
		if len(parts) != 3 {
			continue
		}
		var c int
		if _, err := fmt.Sscan(parts[2], &c); err != nil {
			continue
		}
		if !seenRelated[o] {
			seenRelated[o] = true
			related = append(related, domain.PassageReference{BookID: parts[1], Chapter: c})
		}
		for _, sid := range r.SourceReferenceIDs {
			sourceIDs[sid] = true
		}
	}
	entities := []domain.Entity{}
	for _, e := range s.data.Entities { // fixture order, like the apps
		if ids[e.ID] && e.Type != domain.Passage {
			entities = append(entities, e)
		}
	}
	sources := []domain.SourceReference{}
	for _, src := range s.data.Sources {
		if sourceIDs[src.ID] {
			sources = append(sources, src)
		}
	}
	return domain.PassageContext{
		Reference: domain.PassageReference{BookID: bookID, Chapter: chapter},
		Entities:  entities, RelatedPassages: related, Sources: sources,
	}, nil
}

func (s *Store) Timeline(_ context.Context, entityID string) (domain.Timeline, error) {
	events := []domain.TimelineEvent{}
	names := map[string]string{}
	for _, ev := range s.data.Timeline { // already chronological in the file
		if entityID != "" && !contains(ev.EntityIDs, entityID) {
			continue
		}
		events = append(events, ev)
		for _, id := range ev.EntityIDs {
			if e, ok := s.byID[id]; ok {
				names[id] = e.Name
			}
		}
	}
	return domain.Timeline{Events: events, EntityNames: names}, nil
}

func (s *Store) Search(_ context.Context, query string) ([]domain.Entity, error) {
	q := strings.ToLower(strings.TrimSpace(query))
	out := []domain.Entity{}
	if q == "" {
		return out, nil
	}
	for _, e := range s.data.Entities {
		if e.Type != domain.Passage && strings.Contains(strings.ToLower(e.Name), q) {
			out = append(out, e)
		}
	}
	return out, nil
}

func (s *Store) DailyVersePool(_ context.Context) ([]domain.PassageReference, error) {
	return s.data.DailyVersePool, nil
}

func contains(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}
