import ComposableArchitecture
import Models

/// Reads Scripture text (spec §38).
///
/// Features reach this through `@Dependency(\.bibleClient)` and never see a
/// concrete backend. `chapter` returns one `BiblePassage` per verse so readers
/// can address verses individually; `passage` returns the requested range as a
/// single passage with its verses joined.
@DependencyClient
public struct BibleClient: Sendable {
    public var passage: @Sendable (_ reference: PassageReference) async throws -> BiblePassage
    public var chapter: @Sendable (_ bookId: BookID, _ chapter: Int) async throws -> [BiblePassage]
}

/// Why Scripture could not be read (spec §52: distinguish content unavailable
/// from network problems; never surface raw backend errors).
public enum BibleClientError: Error, Equatable, Sendable {
    /// The book id is not in the canon.
    case unknownBook(BookID)
    /// The chapter is valid but no text is available for it in this translation/source.
    case contentUnavailable(PassageReference)
    /// The chapter exists but the requested verses exceed what it contains.
    case verseOutOfRange(PassageReference, available: Int)
    /// Could not reach the content service and nothing is cached (spec §52).
    case networkUnavailable
}

extension BibleClient: DependencyKey {
    /// bible.helloao.org in the device language, cached on disk, with the
    /// bundled WEB as the English offline fallback. Contracts were stable
    /// before this landed (spec §60 Task 11).
    public static let liveValue = BibleClient.live(language: .current)
    /// Previews never touch the network.
    public static let previewValue = BibleClient.bundled
    // `testValue` is generated by `@DependencyClient`: every endpoint is
    // unimplemented and fails the test unless the test overrides it.
}

extension DependencyValues {
    public var bibleClient: BibleClient {
        get { self[BibleClient.self] }
        set { self[BibleClient.self] = newValue }
    }
}
